name: Filter iCal Events

on:
  schedule:
    # Run the script every hour (you can adjust the cron schedule)
    - cron: '0 * * * *'
  workflow_dispatch:  # Allows manual triggering of the action

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests re

      - name: Run iCal filtering script
        run: python idf-calendar.py

      - name: Commit filtered .ics file
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add filtered_calendar.ics
          git commit -m "Update filtered calendar"
          git push
